// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_BootConnect
void ui_BootConnect_screen_init(void);
void ui_event_BootConnect( lv_event_t * e);
lv_obj_t *ui_BootConnect;
lv_obj_t *ui_kslogo;
lv_obj_t *ui_ConnectingLabel;
lv_obj_t *ui_ConnectingBLEName;
lv_obj_t *ui_ConnectErrorPanel;
lv_obj_t *ui_ConnectBLEErrorTitle;
lv_obj_t *ui_ConnectBLEErrorDescription;
lv_obj_t *ui_M5Battery0Charging;
lv_obj_t *ui_M5Battery0;

// SCREEN: ui_Riding
void ui_Riding_screen_init(void);
lv_obj_t *ui_Riding;
lv_obj_t *ui_SpeedMeter;
lv_obj_t *ui_PWMMeter;
lv_obj_t *ui_SpeedValue;
lv_obj_t *ui_PWMValue;
lv_obj_t *ui_SpeedLabel;
lv_obj_t *ui_PWMLabel;
lv_obj_t *ui_BatteryValue;
lv_obj_t *ui_BatteryIcon;
lv_obj_t *ui_TempIcon;
lv_obj_t *ui_TempValue;
lv_obj_t *ui_CurrentIcon;
lv_obj_t *ui_CurrentValue;
lv_obj_t *ui_VoltIcon;
lv_obj_t *ui_VoltLabel;
lv_obj_t *ui_M5Battery1Charging;
lv_obj_t *ui_M5Battery1;

// SCREEN: ui_Charging
void ui_Charging_screen_init(void);
lv_obj_t *ui_Charging;
lv_obj_t *ui_ChgBatteryGraph;
lv_obj_t *ui_ChgBatteryIcon;
lv_obj_t *ui_ChgTempValue;
lv_obj_t *ui_ChgCurrentIcon;
lv_obj_t *ui_ChgVoltageIcon;
lv_obj_t *ui_ChgTempIcon;
lv_obj_t *ui_ChgVoltageValue;
lv_obj_t *ui_ChgCurrentValue;
lv_obj_t *ui_ChgBatteryValue;
lv_obj_t *ui_M5Battery2Charging;
lv_obj_t *ui_M5Battery2;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BootConnect( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      OnBootConnectLoaded( e );
}
if ( event_code == LV_EVENT_READY) {
      _ui_screen_change( ui_Riding, LV_SCR_LOAD_ANIM_OVER_LEFT, 1000, 0);
}
if ( event_code == LV_EVENT_CANCEL) {
      _ui_screen_change( ui_BootConnect, LV_SCR_LOAD_ANIM_OVER_RIGHT, 1000, 0);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_BootConnect_screen_init();
ui_Riding_screen_init();
ui_Charging_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_BootConnect);
}
