// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#ifndef _SCREEN1_UI_H
#define _SCREEN1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_SpeedMeter;
extern lv_obj_t *ui_PWMMeter;
extern lv_obj_t *ui_SpeedValue;
extern lv_obj_t *ui_PWMValue;
extern lv_obj_t *ui_SpeedLabel;
extern lv_obj_t *ui_PWMLabel;
extern lv_obj_t *ui_BatteryValue;
extern lv_obj_t *ui_BatteryIcon;
extern lv_obj_t *ui_TempIcon;
extern lv_obj_t *ui_TempValue;
extern lv_obj_t *ui_CurrentIcon;
extern lv_obj_t *ui_VoltIcon;
extern lv_obj_t *ui_CurrentValue;
extern lv_obj_t *ui_VoltLabel;
extern lv_obj_t *ui____initial_actions0;

LV_FONT_DECLARE( ui_font_Arcade100);
LV_FONT_DECLARE( ui_font_FontAwesome35);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
