// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#ifndef _SCREEN1_UI_H
#define _SCREEN1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_BootConnect
void ui_BootConnect_screen_init(void);
void ui_event_BootConnect( lv_event_t * e);
extern lv_obj_t *ui_BootConnect;
extern lv_obj_t *ui_kslogo;
extern lv_obj_t *ui_ConnectingLabel;
extern lv_obj_t *ui_ConnectingBLEName;
extern lv_obj_t *ui_ConnectErrorPanel;
extern lv_obj_t *ui_ConnectBLEErrorTitle;
extern lv_obj_t *ui_ConnectBLEErrorDescription;
// SCREEN: ui_Riding
void ui_Riding_screen_init(void);
extern lv_obj_t *ui_Riding;
extern lv_obj_t *ui_SpeedMeter;
extern lv_obj_t *ui_PWMMeter;
extern lv_obj_t *ui_SpeedValue;
extern lv_obj_t *ui_PWMValue;
extern lv_obj_t *ui_SpeedLabel;
extern lv_obj_t *ui_PWMLabel;
extern lv_obj_t *ui_BatteryValue;
extern lv_obj_t *ui_BatteryIcon;
extern lv_obj_t *ui_TempIcon;
extern lv_obj_t *ui_TempValue;
extern lv_obj_t *ui_CurrentIcon;
extern lv_obj_t *ui_CurrentValue;
extern lv_obj_t *ui_VoltIcon;
extern lv_obj_t *ui_VoltLabel;
// SCREEN: ui_Charging
void ui_Charging_screen_init(void);
extern lv_obj_t *ui_Charging;
extern lv_obj_t *ui_ChgBatteryGraph;
extern lv_obj_t *ui_ChgBatteryIcon;
extern lv_obj_t *ui_ChgTempValue;
extern lv_obj_t *ui_ChgCurrentIcon;
extern lv_obj_t *ui_ChgVoltageIcon;
extern lv_obj_t *ui_ChgTempIcon;
extern lv_obj_t *ui_ChgVoltageValue;
extern lv_obj_t *ui_ChgCurrentValue;
extern lv_obj_t *ui_ChgBatteryValue;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_bg_png);   // assets/bg.png
LV_IMG_DECLARE( ui_img_ks_logo_png);   // assets/ks_logo.png

LV_FONT_DECLARE( ui_font_Arcade100);
LV_FONT_DECLARE( ui_font_FontAwesome35);
LV_FONT_DECLARE( ui_font_FontAwesome45);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
