// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#include "ui.h"
#include "esp_log.h"
#include "s22_display.h"

#include "ble/ble.h"

#define BOOT_CONNECT_TAG "ui:boot_connect"

void OnBootConnectLoaded(lv_event_t *e)
{
	// Connect to wheel
	ESP_LOGI(BOOT_CONNECT_TAG, "OnBootConnectLoaded");
	start_ble_scan();
}
