// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#include "../ui.h"

void ui_BootConnect_screen_init(void)
{
ui_BootConnect = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BootConnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_BootConnect, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_tiled(ui_BootConnect, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_kslogo = lv_img_create(ui_BootConnect);
lv_img_set_src(ui_kslogo, &ui_img_ks_logo_png);
lv_obj_set_width( ui_kslogo, LV_SIZE_CONTENT);  /// 199
lv_obj_set_height( ui_kslogo, LV_SIZE_CONTENT);   /// 76
lv_obj_set_x( ui_kslogo, 0 );
lv_obj_set_y( ui_kslogo, -35 );
lv_obj_set_align( ui_kslogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_kslogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_kslogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ConnectingLabel = lv_label_create(ui_BootConnect);
lv_obj_set_width( ui_ConnectingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ConnectingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ConnectingLabel, 0 );
lv_obj_set_y( ui_ConnectingLabel, 60 );
lv_obj_set_align( ui_ConnectingLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ConnectingLabel,"Connecting to wheel");
lv_obj_set_style_text_font(ui_ConnectingLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConnectingBLEName = lv_label_create(ui_BootConnect);
lv_obj_set_width( ui_ConnectingBLEName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ConnectingBLEName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ConnectingBLEName, 0 );
lv_obj_set_y( ui_ConnectingBLEName, 95 );
lv_obj_set_align( ui_ConnectingBLEName, LV_ALIGN_CENTER );
lv_label_set_text(ui_ConnectingBLEName,"KSN-S22-xxxxx");
lv_obj_set_style_text_font(ui_ConnectingBLEName, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConnectErrorPanel = lv_obj_create(ui_BootConnect);
lv_obj_set_width( ui_ConnectErrorPanel, 240);
lv_obj_set_height( ui_ConnectErrorPanel, 180);
lv_obj_set_align( ui_ConnectErrorPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ConnectErrorPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ConnectErrorPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_ConnectErrorPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ConnectErrorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ConnectErrorPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ConnectErrorPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConnectBLEErrorTitle = lv_label_create(ui_ConnectErrorPanel);
lv_obj_set_width( ui_ConnectBLEErrorTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ConnectBLEErrorTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ConnectBLEErrorTitle, 0 );
lv_obj_set_y( ui_ConnectBLEErrorTitle, -50 );
lv_obj_set_align( ui_ConnectBLEErrorTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_ConnectBLEErrorTitle," Bluetooth Error ");
lv_obj_set_style_text_color(ui_ConnectBLEErrorTitle, lv_color_hex(0xDBFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ConnectBLEErrorTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ConnectBLEErrorTitle, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConnectBLEErrorDescription = lv_label_create(ui_ConnectErrorPanel);
lv_obj_set_width( ui_ConnectBLEErrorDescription, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ConnectBLEErrorDescription, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ConnectBLEErrorDescription, 0 );
lv_obj_set_y( ui_ConnectBLEErrorDescription, 30 );
lv_obj_set_align( ui_ConnectBLEErrorDescription, LV_ALIGN_CENTER );
lv_label_set_text(ui_ConnectBLEErrorDescription,"Error Description goes\nhere...");
lv_obj_set_style_text_color(ui_ConnectBLEErrorDescription, lv_color_hex(0xDBFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ConnectBLEErrorDescription, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ConnectBLEErrorDescription, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_M5Battery0Charging = lv_label_create(ui_BootConnect);
lv_obj_set_width( ui_M5Battery0Charging, 40);
lv_obj_set_height( ui_M5Battery0Charging, 35);
lv_obj_set_x( ui_M5Battery0Charging, 135 );
lv_obj_set_y( ui_M5Battery0Charging, -105 );
lv_obj_set_align( ui_M5Battery0Charging, LV_ALIGN_CENTER );
lv_label_set_text(ui_M5Battery0Charging,"");
lv_obj_set_style_text_color(ui_M5Battery0Charging, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_M5Battery0Charging, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_M5Battery0Charging, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_M5Battery0Charging, &ui_font_FontAwesome35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_M5Battery0 = lv_label_create(ui_BootConnect);
lv_obj_set_width( ui_M5Battery0, 40);
lv_obj_set_height( ui_M5Battery0, 35);
lv_obj_set_x( ui_M5Battery0, 135 );
lv_obj_set_y( ui_M5Battery0, -105 );
lv_obj_set_align( ui_M5Battery0, LV_ALIGN_CENTER );
lv_label_set_text(ui_M5Battery0,"");
lv_obj_set_style_text_align(ui_M5Battery0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_M5Battery0, &ui_font_FontAwesome35, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BootConnect, ui_event_BootConnect, LV_EVENT_ALL, NULL);

}
