// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#include "../ui.h"

void ui_BootConnect_screen_init(void)
{
ui_BootConnect = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BootConnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_BootConnect, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_tiled(ui_BootConnect, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_kslogo = lv_img_create(ui_BootConnect);
lv_img_set_src(ui_kslogo, &ui_img_ks_logo_png);
lv_obj_set_width( ui_kslogo, LV_SIZE_CONTENT);  /// 199
lv_obj_set_height( ui_kslogo, LV_SIZE_CONTENT);   /// 76
lv_obj_set_x( ui_kslogo, 0 );
lv_obj_set_y( ui_kslogo, -20 );
lv_obj_set_align( ui_kslogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_kslogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_kslogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_BootConnect);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, 80 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Connecting to wheel");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

}
