// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: screen1

#include "../ui.h"

void ui_Charging_screen_init(void)
{
ui_Charging = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Charging, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Charging, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_tiled(ui_Charging, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgBatteryGraph = lv_chart_create(ui_Charging);
lv_obj_set_width( ui_ChgBatteryGraph, 280);
lv_obj_set_height( ui_ChgBatteryGraph, 100);
lv_obj_set_x( ui_ChgBatteryGraph, 20 );
lv_obj_set_y( ui_ChgBatteryGraph, 40 );
lv_obj_set_align( ui_ChgBatteryGraph, LV_ALIGN_CENTER );
lv_chart_set_type( ui_ChgBatteryGraph, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_ChgBatteryGraph, 13);
lv_chart_set_range( ui_ChgBatteryGraph, LV_CHART_AXIS_PRIMARY_Y, 64, 87);
lv_chart_set_axis_tick( ui_ChgBatteryGraph, LV_CHART_AXIS_PRIMARY_X, 10, 5, 7, 2, true, 50);
lv_chart_set_axis_tick( ui_ChgBatteryGraph, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_ChgBatteryGraph, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_ChgBatteryGraph_series_1 = lv_chart_add_series(ui_ChgBatteryGraph, lv_color_hex(0x6269EF), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ChgBatteryGraph_series_1_array[] = { 66,68,70,72,73,75,77,78,80,82,84,85,86 };
lv_chart_set_ext_y_array(ui_ChgBatteryGraph, ui_ChgBatteryGraph_series_1, ui_ChgBatteryGraph_series_1_array);
lv_chart_series_t* ui_ChgBatteryGraph_series_2 = lv_chart_add_series(ui_ChgBatteryGraph, lv_color_hex(0xE53838), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ChgBatteryGraph_series_2_array[] = { 64,64,66,68,69,69,72,75,77,78,79,80,81 };
lv_chart_set_ext_y_array(ui_ChgBatteryGraph, ui_ChgBatteryGraph_series_2, ui_ChgBatteryGraph_series_2_array);
lv_chart_series_t* ui_ChgBatteryGraph_series_3 = lv_chart_add_series(ui_ChgBatteryGraph, lv_color_hex(0x5DED5A), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ChgBatteryGraph_series_3_array[] = { 67,68,72,73,74,76,77,80,81,83,84,85,87 };
lv_chart_set_ext_y_array(ui_ChgBatteryGraph, ui_ChgBatteryGraph_series_3, ui_ChgBatteryGraph_series_3_array);

ui_ChgBatteryIcon = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgBatteryIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgBatteryIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgBatteryIcon, -120 );
lv_obj_set_y( ui_ChgBatteryIcon, -40 );
lv_obj_set_align( ui_ChgBatteryIcon, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgBatteryIcon,"");
lv_obj_set_style_text_color(ui_ChgBatteryIcon, lv_color_hex(0x40BC30), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ChgBatteryIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ChgBatteryIcon, &ui_font_FontAwesome45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgTempValue = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgTempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgTempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgTempValue, 120 );
lv_obj_set_y( ui_ChgTempValue, -90 );
lv_obj_set_align( ui_ChgTempValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgTempValue,"85");
lv_obj_set_style_text_font(ui_ChgTempValue, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgCurrentIcon = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgCurrentIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgCurrentIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgCurrentIcon, -40 );
lv_obj_set_y( ui_ChgCurrentIcon, -40 );
lv_obj_set_align( ui_ChgCurrentIcon, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgCurrentIcon,"");
lv_obj_set_style_text_color(ui_ChgCurrentIcon, lv_color_hex(0x40BC30), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ChgCurrentIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ChgCurrentIcon, &ui_font_FontAwesome45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgVoltageIcon = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgVoltageIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgVoltageIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgVoltageIcon, 40 );
lv_obj_set_y( ui_ChgVoltageIcon, -40 );
lv_obj_set_align( ui_ChgVoltageIcon, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgVoltageIcon,"");
lv_obj_set_style_text_color(ui_ChgVoltageIcon, lv_color_hex(0x40BC30), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ChgVoltageIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ChgVoltageIcon, &ui_font_FontAwesome45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgTempIcon = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgTempIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgTempIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgTempIcon, 120 );
lv_obj_set_y( ui_ChgTempIcon, -40 );
lv_obj_set_align( ui_ChgTempIcon, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgTempIcon,"");
lv_obj_set_style_text_color(ui_ChgTempIcon, lv_color_hex(0x40BC30), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ChgTempIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ChgTempIcon, &ui_font_FontAwesome45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgVoltageValue = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgVoltageValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgVoltageValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgVoltageValue, 40 );
lv_obj_set_y( ui_ChgVoltageValue, -90 );
lv_obj_set_align( ui_ChgVoltageValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgVoltageValue,"118V");
lv_obj_set_style_text_font(ui_ChgVoltageValue, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgCurrentValue = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgCurrentValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgCurrentValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgCurrentValue, -40 );
lv_obj_set_y( ui_ChgCurrentValue, -90 );
lv_obj_set_align( ui_ChgCurrentValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgCurrentValue,"-5A");
lv_obj_set_style_text_font(ui_ChgCurrentValue, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChgBatteryValue = lv_label_create(ui_Charging);
lv_obj_set_width( ui_ChgBatteryValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChgBatteryValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChgBatteryValue, -120 );
lv_obj_set_y( ui_ChgBatteryValue, -90 );
lv_obj_set_align( ui_ChgBatteryValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChgBatteryValue,"84%");
lv_obj_set_style_text_font(ui_ChgBatteryValue, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

}
